baseurl: "/"
title: "Libris Hugo Theme"
page_load_js: "assets/js/main.js"
menu:
  main:
    - identifier: layouts
      name: Sample Layouts
      url: "#"
      weight: 5
    - identifier: github
      name: GitHub
      url: "https://github.com/pjeby/libris-hugo/"
      weight: 6

markup:
  highlight:
    codeFences: false
  goldmark:
    renderer:
      unsafe: true

disableKinds:
  - RSS
  - taxonomyTerm

relativeURLs: true

themesDir: ../..
theme: libris-hugo
