baseurl: "/"
title: "Stackbit Libris Theme"
page_load_js: "assets/js/main.js"
menu:
  main:
    - identifier: layouts
      name: Sample Layouts
      url: "#"
      weight: 5
    - identifier: github
      name: GitHub
      url: "https://github.com/pjeby/libris-hugo/"
      weight: 6

markup:
  highlight:
    codeFences: false
  goldmark:
    renderer:
      unsafe: true

disableKinds:
  - RSS
  - taxonomyTerm

sass:
  input_file: sass/main.scss.njk
  output_file: assets/css/main.css
  indentWidth: 4
  outputStyle: nested
  precision: 10

relativeURLs: true
uglyurls: true

themesDir: ../..
theme: libris-hugo
